[graph]
all-features = true

[licenses]
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "ISC",
    "MIT",
]
exceptions = [
    { crate = "unicode-ident", allow = ["Unicode-3.0"] },
    { crate = "webpki-roots", allow = ["CDLA-Permissive-2.0"] },
]

[bans]
skip = [
    "windows-sys@0.60",
]
skip-tree = [
    { crate = "windows-sys@0.52", depth = 3 },
]
